/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mypower24.devparamapp;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author henry
 */
public class MainFrame extends javax.swing.JFrame {

    private File openFile;
    private Map<String, DevParamSetting> paramSettingList;
    private DevParamSetting selectedSetting;
    private final List<String> cbxTypeValues = new ArrayList<>();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            initComponents();
            cbxTypeValues.add("inputNumber");
            cbxTypeValues.add("inputText");
            cbxTypeValues.add("switch");
            cbxTypeValues.add("dropDown");
            cbxTypeValues.add("command");
//            cbxTypeValues.add({"inputNumber", "inputText", "switch", "dropDown", "command"});
//                    = new ArrayList<>( {

            for (String cbxTypeValue : cbxTypeValues) {
                cbxType.addItem(cbxTypeValue);
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogDDConfig = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDdItemsList = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        txtDDConfLabel = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDDConfVal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnDdDeleteItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cbxType = new javax.swing.JComboBox<>();
        txtParamUnit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtParamTitle = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtParamDesc = new javax.swing.JTextArea();
        txtParamReg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreview = new javax.swing.JTextPane();
        btnSave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstParamList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        btnOpenFile = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        lblOpenFile = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtParamName = new javax.swing.JTextField();
        btnDdConfig = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();

        dialogDDConfig.setTitle("DropDown Config");
        dialogDDConfig.setAlwaysOnTop(true);
        dialogDDConfig.setMinimumSize(new java.awt.Dimension(500, 300));
        dialogDDConfig.setModal(true);
        dialogDDConfig.setPreferredSize(new java.awt.Dimension(500, 300));
        dialogDDConfig.setSize(new java.awt.Dimension(600, 350));

        jLabel12.setText("Label");

        txtDdItemsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(txtDdItemsList);

        jLabel13.setText("Items");

        jLabel14.setText("Value");

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnDdDeleteItem.setText("Delete");
        btnDdDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDdDeleteItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogDDConfigLayout = new javax.swing.GroupLayout(dialogDDConfig.getContentPane());
        dialogDDConfig.getContentPane().setLayout(dialogDDConfigLayout);
        dialogDDConfigLayout.setHorizontalGroup(
            dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDDConfigLayout.createSequentialGroup()
                .addGroup(dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogDDConfigLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtDDConfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtDDConfVal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogDDConfigLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDdDeleteItem)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap())
        );
        dialogDDConfigLayout.setVerticalGroup(
            dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogDDConfigLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogDDConfigLayout.createSequentialGroup()
                        .addGroup(dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogDDConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDDConfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDDConfVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDdDeleteItem)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Device Param Configurator");

        cbxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTypeActionPerformed(evt);
            }
        });

        txtParamUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParamUnitActionPerformed(evt);
            }
        });
        txtParamUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParamUnitKeyTyped(evt);
            }
        });

        jLabel5.setText("Unit");

        jLabel6.setText("Register");

        txtParamTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParamTitleActionPerformed(evt);
            }
        });
        txtParamTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParamTitleKeyTyped(evt);
            }
        });

        txtParamDesc.setColumns(20);
        txtParamDesc.setLineWrap(true);
        txtParamDesc.setRows(5);
        txtParamDesc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtParamDescPropertyChange(evt);
            }
        });
        txtParamDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParamDescKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtParamDesc);

        txtParamReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParamRegActionPerformed(evt);
            }
        });
        txtParamReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParamRegKeyTyped(evt);
            }
        });

        jLabel3.setText("Title");

        jLabel4.setText("Description");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("JSON Preview");

        txtPreview.setEditable(false);
        jScrollPane1.setViewportView(txtPreview);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel9.setText("Type");

        lstParamList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstParamList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstParamList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstParamListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstParamList);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Select To Edit");

        btnOpenFile.setText("Open from file");
        btnOpenFile.setToolTipText("");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        btnAddNew.setText("Add New");

        lblOpenFile.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblOpenFile.setText("jLabel11");

        jLabel11.setText("Param Name");

        txtParamName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParamNameKeyTyped(evt);
            }
        });

        btnDdConfig.setText("Options");
        btnDdConfig.setToolTipText("Edit options for Dropdown");
        btnDdConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDdConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtParamReg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave)
                            .addComponent(txtParamUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtParamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDdConfig)
                                .addGap(94, 94, 94)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(206, 206, 206)
                                .addComponent(txtParamName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnOpenFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOpenFile)
                                .addGap(152, 152, 152)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 251, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblOpenFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtParamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(btnDdConfig))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtParamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtParamUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtParamReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave)
                                .addGap(23, 23, 23))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOpenFile)
                            .addComponent(btnAddNew))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create", jPanel1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CreatedParams");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Preview");

        jTextPane2.setEditable(false);
        jScrollPane4.setViewportView(jTextPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Overview", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtParamRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParamRegActionPerformed
        updatePreview();
    }//GEN-LAST:event_txtParamRegActionPerformed

    private void cbxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTypeActionPerformed
        if (cbxTypeValues.get(cbxType.getSelectedIndex()).equals("dropDown")) {
            btnDdConfig.setVisible(true);
            DropDownParam ddParam = new DropDownParam(selectedSetting);
            selectedSetting = ddParam;

//            selectedSetting = (DropDownParam) selectedSetting;
        } else {
            selectedSetting = (DevParamSetting) selectedSetting;
            btnDdConfig.setVisible(false);
        }
        if (selectedSetting != null) {
            selectedSetting.setType((String) cbxType.getSelectedItem());
            updatePreview();
        }
    }//GEN-LAST:event_cbxTypeActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        int showOpenDialog = jFileChooser.showOpenDialog(jPanel1);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
            openFile = jFileChooser.getSelectedFile();
            lblOpenFile.setText(openFile.getName());
            paramSettingList = FileProcessor.processFileAuto(openFile);
//            lst.addAll(processFileAuto.keySet());
            Vector<String> vector = new Vector<>(paramSettingList.keySet());
            Collections.sort(vector);
            lstParamList.setListData(vector);
//            for (DevParamSetting devParamSetting : processFileAuto) {
//                lstParamList.(devParamSetting.getParamName(), null);
//            }
        }

    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void lstParamListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstParamListValueChanged
        String selectedValue = lstParamList.getSelectedValue();
        selectedSetting = paramSettingList.get(selectedValue);
        txtParamName.setText(selectedSetting.getParamName());
        txtParamDesc.setText(selectedSetting.getParamDesc());
        txtParamTitle.setText(selectedSetting.getTitle());
        txtParamUnit.setText(selectedSetting.getUnit());

        cbxType.setSelectedIndex(cbxTypeValues.indexOf(selectedSetting.getType()));
        updatePreview();

    }//GEN-LAST:event_lstParamListValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String label = txtDDConfLabel.getText().trim();
        String value = txtDDConfVal.getText().trim();
        if (!label.equals("") && !value.equals("") && selectedSetting instanceof DropDownParam) {
            DropDownOption dropDownOption = new DropDownOption();
            dropDownOption.setLabel(label);
            dropDownOption.setValue(value);

            DropDownParam param = (DropDownParam) selectedSetting;
            param.getOptions().add(dropDownOption);
            updateDdItemList();
        }
        updatePreview();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDdConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDdConfigActionPerformed
        dialogDDConfig.setVisible(true);
        if (selectedSetting instanceof DropDownParam) {
            DropDownParam param = (DropDownParam) selectedSetting;
            List<DropDownOption> options = param.getOptions();
            Vector<String> lst = new Vector<>();
            for (DropDownOption option : options) {
                String item = option.getLabel() + " : " + option.getValue();
                lst.add(item);
            }
            txtDdItemsList.setListData(lst);
        }
        updatePreview();
    }//GEN-LAST:event_btnDdConfigActionPerformed

    private void btnDdDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDdDeleteItemActionPerformed
        if (selectedSetting instanceof DropDownParam) {
            DropDownParam param = (DropDownParam) selectedSetting;
            List<DropDownOption> options = param.getOptions();
            String selectedValue = txtDdItemsList.getSelectedValue();
            for (DropDownOption option : options) {
                if ((option.getLabel() + " : " + option.getValue()).equals(selectedValue)) {
                    options.remove(option);
                    break;
                }
            }
            updateDdItemList();
            updatePreview();

        }
    }//GEN-LAST:event_btnDdDeleteItemActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        updatePreview();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtParamTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParamTitleActionPerformed
        updatePreview();
    }//GEN-LAST:event_txtParamTitleActionPerformed

    private void txtParamUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParamUnitActionPerformed
        updatePreview();
    }//GEN-LAST:event_txtParamUnitActionPerformed

    private void txtParamDescPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtParamDescPropertyChange
        updatePreview();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParamDescPropertyChange

    private void txtParamDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParamDescKeyTyped
        updatePreview();
    }//GEN-LAST:event_txtParamDescKeyTyped

    private void txtParamRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParamRegKeyTyped
        updatePreview();
    }//GEN-LAST:event_txtParamRegKeyTyped

    private void txtParamUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParamUnitKeyTyped
        updatePreview();
    }//GEN-LAST:event_txtParamUnitKeyTyped

    private void txtParamTitleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParamTitleKeyTyped
       updatePreview();
    }//GEN-LAST:event_txtParamTitleKeyTyped

    private void txtParamNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParamNameKeyTyped
        updatePreview();
    }//GEN-LAST:event_txtParamNameKeyTyped

    private void updatePreview() {
        try {
            if (selectedSetting != null) {

                selectedSetting.setParamDesc(txtParamDesc.getText());
                selectedSetting.setParamName(txtParamName.getText());
                selectedSetting.setUnit(txtParamUnit.getText());
                selectedSetting.setTitle(txtParamTitle.getText());
                ObjectMapper om = new ObjectMapper();
                String writeValueAsString = om.writerWithDefaultPrettyPrinter().writeValueAsString(selectedSetting);
                txtPreview.setText(writeValueAsString);
            }
        } catch (JsonProcessingException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateDdItemList() {
        if (selectedSetting instanceof DropDownParam) {
            DropDownParam param = (DropDownParam) selectedSetting;
            List<DropDownOption> options = param.getOptions();
            Vector<String> lst = new Vector<>();
            for (DropDownOption option : options) {
                String item = option.getLabel() + " : " + option.getValue();
                lst.add(item);
            }
            txtDdItemsList.setListData(lst);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnDdConfig;
    private javax.swing.JButton btnDdDeleteItem;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JDialog dialogDDConfig;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel lblOpenFile;
    private javax.swing.JList<String> lstParamList;
    private javax.swing.JTextField txtDDConfLabel;
    private javax.swing.JTextField txtDDConfVal;
    private javax.swing.JList<String> txtDdItemsList;
    private javax.swing.JTextArea txtParamDesc;
    private javax.swing.JTextField txtParamName;
    private javax.swing.JTextField txtParamReg;
    private javax.swing.JTextField txtParamTitle;
    private javax.swing.JTextField txtParamUnit;
    private javax.swing.JTextPane txtPreview;
    // End of variables declaration//GEN-END:variables
}
